// Copyright Punal Manalan. All Rights Reserved.
// A_WCG - Atomic Web Component Generator

#include "awcg_cpp_generator.h"
#include <sstream>
#include <algorithm>
#include <ctime>

namespace awcg {

namespace {
    // Helper to generate chunked output parts for large strings
    void emitChunkedParts(std::ostringstream& src, const std::string& content, const std::string& comment = "") {
        if (!comment.empty()) {
             src << "    // " << comment << "\n";
        }
        
        const size_t MAX_CHUNK_SIZE = 2048; // Safe limit for MSVC string literals
        size_t total = content.length();
        size_t offset = 0;
        
        while (offset < total) {
            size_t chunkSize = std::min(MAX_CHUNK_SIZE, total - offset);
            std::string chunk = content.substr(offset, chunkSize);
            
            src << "    Parts.Add(TEXT(R\"JSON(" << chunk << ")JSON\"));\n";
            
            offset += chunkSize;
        }
        src << "\n";
    }
}

std::string CppGenerator::generateHeader(const ParsedWebSource& source,
                                         const std::string& className,
                                         const std::string& moduleName,
                                         const JSONGenerator::ChunkedSpec& chunkedSpec,
                                         std::vector<Diagnostic>& /*outDiagnostics*/) {
    std::ostringstream header;
    
    // File header
    header << "// Auto-generated by A_WCG - DO NOT EDIT\n";
    header << "// Source: " << source.htmlPath << "\n";
    
    time_t now = time(nullptr);
    char timeStr[64];
    strftime(timeStr, sizeof(timeStr), "%Y-%m-%d %H:%M:%S", localtime(&now));
    header << "// Generated: " << timeStr << "\n\n";
    
    header << "#pragma once\n\n";
    header << "#include \"CoreMinimal.h\"\n";
    header << "#include \"Blueprint/UserWidget.h\"\n";
    header << "#include \"Components/CanvasPanel.h\"\n";
    header << "#include \"Components/VerticalBox.h\"\n";
    header << "#include \"Components/HorizontalBox.h\"\n";
    header << "#include \"Components/Button.h\"\n";
    header << "#include \"MWCS_TransparentButton.h\"\n";
    header << "#include \"Components/TextBlock.h\"\n";
    header << "#include \"Components/Image.h\"\n";
    header << "#include \"Components/EditableTextBox.h\"\n";
    header << "#include \"" << className << ".generated.h\"\n\n";
    
    // Class declaration
    std::string apiMacro = moduleName;
    std::transform(apiMacro.begin(), apiMacro.end(), apiMacro.begin(), ::toupper);
    apiMacro += "_API";
    
    header << "/**\n";
    header << " * " << className << "\n";
    header << " * Generated from: " << source.htmlPath << "\n";
    header << " */\n";
    header << "UCLASS()\n";
    header << "class " << apiMacro << " U" << className << " : public UUserWidget\n";
    header << "{\n";
    header << "    GENERATED_BODY()\n\n";
    header << "public:\n";
    header << "    U" << className << "(const FObjectInitializer& ObjectInitializer);\n\n";
    header << "protected:\n";
    header << "    virtual void NativeConstruct() override;\n\n";
    header << "    /**\n";
    header << "     * Returns the P_MWCS widget specification JSON\n";
    header << "     */\n";
    header << "    UFUNCTION(BlueprintPure, Category = \"MWCS\")\n";
    header << "    FString GetWidgetSpec() const;\n\n";
    
    // Widget bindings from ChunkedSpec to ensure consistency
    if (!chunkedSpec.bindingList.empty()) {
        header << "    // Widget Bindings\n";
        for (const auto& binding : chunkedSpec.bindingList) {
            header << "    UPROPERTY(meta = (BindWidget))\n";
            header << "    " << binding.second << "* " << binding.first << ";\n\n";
        }
    }
    
    header << "};\n";
    
    return header.str();
}

std::string CppGenerator::generateSource(const ParsedWebSource& source,
                                          const std::string& className,
                                          const std::string& /*moduleName*/,
                                          const JSONGenerator::ChunkedSpec& chunkedSpec,
                                          std::vector<Diagnostic>& /*outDiagnostics*/) {
    std::ostringstream src;
    
    // File header
    src << "// Auto-generated by A_WCG - DO NOT EDIT\n";
    src << "// Source: " << source.htmlPath << "\n\n";
    
    src << "#include \"" << className << ".h\"\n\n";
    
    // Constructor
    src << "U" << className << "::U" << className << "(const FObjectInitializer& ObjectInitializer)\n";
    src << "    : Super(ObjectInitializer)\n";
    src << "{\n";
    src << "}\n\n";
    
    // NativeConstruct
    src << "void U" << className << "::NativeConstruct()\n";
    src << "{\n";
    src << "    Super::NativeConstruct();\n";
    src << "}\n\n";

    // GetWidgetSpec - Implements Clean Style
    src << "FString U" << className << "::GetWidgetSpec() const\n";
    src << "{\n";
    src << "    static FString Spec;\n\n";
    src << "    if (!Spec.IsEmpty())\n";
    src << "    {\n";
    src << "        return Spec;\n";
    src << "    }\n\n";
    
    // Calculate estimated parts
    size_t totalLen = chunkedSpec.metadata.length() + chunkedSpec.hierarchy.length() + 
                      chunkedSpec.design.length() + chunkedSpec.bindings.length();
    size_t estimatedParts = (totalLen / 2048) + 10;
    
    src << "    TArray<FString> Parts;\n";
    src << "    Parts.Reserve(" << estimatedParts << ");\n\n";
    
    // Part 1: Metadata + Hierarchy
    // Merge them first then chunk, or chunk individually. Merging ensures valid JSON transitions if chunking isn't smart about boundaries?
    // Actually we just concat everything.
    // Note: We need the commas between sections which were previously inline.
    
    std::string part1 = chunkedSpec.metadata + ",\n\n" + chunkedSpec.hierarchy + ",\n";
    emitChunkedParts(src, part1, "--- PART 1: Metadata / Hierarchy ---");

    // Part 2: Design
    std::string part2 = chunkedSpec.design + ",\n";
    emitChunkedParts(src, part2, "--- PART 2: Design ---");

    // Part 3: Bindings
    std::string part3 = chunkedSpec.bindings + "\n}\n"; 
    emitChunkedParts(src, part3, "--- PART 3: Bindings ---");
    
    src << "    Spec = FString::Join(Parts, TEXT(\"\"));\n";
    src << "    return Spec;\n";
    src << "}\n";
    
    return src.str();
}

void CppGenerator::collectBindings(const DOMNode& node,
                                   std::vector<std::pair<std::string, std::string>>& outBindings) {
    // Unused in favor of ChunkedSpec.bindingList
}

} // namespace awcg
